[package]
name = "rustlink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = {version = "4", features = ["derive"]}
probe-rs = "0.18.0"
